# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assignment6_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class assignment6_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(896, 667)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 50, 761, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graphbox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graphbox.setContentsMargins(0, 0, 0, 0)
        self.graphbox.setObjectName("graphbox")
        self.dd_waveform = QtWidgets.QComboBox(Form)
        self.dd_waveform.setGeometry(QtCore.QRect(70, 500, 161, 41))
        self.dd_waveform.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dd_waveform.setStyleSheet("font: 9pt \"Times New Roman\";")
        self.dd_waveform.setObjectName("dd_waveform")
        self.dd_waveform.addItem("")
        self.dd_waveform.addItem("")
        self.dd_waveform.addItem("")
        self.pb = QtWidgets.QPushButton(Form)
        self.pb.setGeometry(QtCore.QRect(340, 580, 211, 51))
        self.pb.setObjectName("pb")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 480, 81, 16))
        self.label.setAcceptDrops(False)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 11pt \"SimSun\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 480, 131, 16))
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("font: 11pt \"SimSun\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(500, 480, 141, 16))
        self.label_3.setAcceptDrops(False)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("font: 11pt \"SimSun\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(710, 480, 101, 16))
        self.label_4.setAcceptDrops(False)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("font: 11pt \"SimSun\";")
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_frequency = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_frequency.setGeometry(QtCore.QRect(270, 500, 161, 41))
        self.doubleSpinBox_frequency.setDecimals(3)
        self.doubleSpinBox_frequency.setMaximum(200.0)
        self.doubleSpinBox_frequency.setSingleStep(0.001)
        self.doubleSpinBox_frequency.setProperty("value", 100.0)
        self.doubleSpinBox_frequency.setObjectName("doubleSpinBox_frequency")
        self.spinBox_amplitude = QtWidgets.QSpinBox(Form)
        self.spinBox_amplitude.setGeometry(QtCore.QRect(480, 500, 161, 41))
        self.spinBox_amplitude.setMaximum(10)
        self.spinBox_amplitude.setProperty("value", 5)
        self.spinBox_amplitude.setObjectName("spinBox_amplitude")
        self.spinBox_offset = QtWidgets.QSpinBox(Form)
        self.spinBox_offset.setGeometry(QtCore.QRect(670, 500, 161, 41))
        self.spinBox_offset.setMaximum(10)
        self.spinBox_offset.setProperty("value", 0)
        self.spinBox_offset.setObjectName("spinBox_offset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dd_waveform.setItemText(0, _translate("Form", "SINE"))
        self.dd_waveform.setItemText(1, _translate("Form", "SQUARE"))
        self.dd_waveform.setItemText(2, _translate("Form", "RAMP"))
        self.pb.setText(_translate("Form", "Suprise Me!"))
        self.label.setText(_translate("Form", "WAVEFORM"))
        self.label_2.setText(_translate("Form", "FREQUENCY(kHz)"))
        self.label_3.setText(_translate("Form", "AMPLITUDE(Vpp)"))
        self.label_4.setText(_translate("Form", "OFFSET(VDC)"))
